### ISSUE TITLE
go仓库合并转发显示不全

### ISSUE THREAD

**Issue by 495luke** [daycold1000/csgo-nb#1]
上限限制了100条，能否做成套娃那种合并中分颜色套娃合并消息，或者更换为图片显示之类的。

**Comment by daycold1000** [comment]
你好伙计~在目前只有两种武器箱的情况下，转发消息一共只有47条并没有100条，且增加一种武器也同样只会增加1条消息。同时如果更换为图片显示，在编写之初就有考虑过能否以图片方式展示，以及图片能否过审以及如何排版（主要是武器太多了）。
尝试过多种版本，目前为止是最佳方案。
当然你有更好的想法可以在下面继续comment或者使用email发送到miao-time@foxmail.com，谢谢提出意见！

**Comment by daycold1000** [comment]
同时考虑过在合并消息里再合并，发现我并不会做，同样的，在索引仓库中（我浏览过的）的插件也没有写过类似的代码，因此你所说的“套娃那种合并中分颜色套娃合并消息”（在合并消息中按照稀有度再次分类为新的合并消息）不会做呜呜呜~（想法确实不错，有空我来试试！）

**Comment by 495luke** [comment]
看到了，我看结尾还有一个红稀有度列表，我以为没显示全，还有这个补货有指令吗，凌晨5点之后我看没有补货，不知道什么bug
