### ISSUE TITLE
有人真在开箱中！

### ISSUE THREAD

**Issue by yuyue31** [daycold1000/csgo-nb#2]
大佬您好，请问遇到这个问题怎么解决

**Comment by daycold1000** [comment]
是否有人在开箱的时候关闭了机器人？

**Comment by yuyue31** [comment]
可能是这样的，大佬这样该怎么解决



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月18日(周日) 上午10:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [daycold1000/csgo-nb] 有人真在开箱中！ (Issue #2)




 
是否有人在开箱的时候关闭了机器人？

**Comment by daycold1000** [comment]
那我过会添加一个强制解锁指令，请注意更新并覆盖原代码。
请注意：确保真的卡住了，因为代码原因，数据库是一条条写入的，同时两个玩家一起写入会相互覆盖数据
↑

**Comment by daycold1000** [comment]
已上传，现可以覆盖代码文件了

**Comment by daycold1000** [comment]
有问题可以直接通过miao-time@foxmail.com沟通

**Comment by yuyue31** [comment]
好的，谢谢大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月18日(周日) 上午10:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [daycold1000/csgo-nb] 有人真在开箱中！ (Issue #2)




 
已上传，现可以覆盖代码文件了
